name: HannahPay Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: emailPrefix
    value: test-user
  - key: signupPassword
    value: ''
  - key: namePrefix
    value: Test User
  - key: loginPassword
    value: ''
  - key: accessToken
    value: ''
  - key: userId
    value: ''
  - key: userEmail
    value: ''
